#!/usr/bin/env ruby

ADDED_OR_MODIFIED = /A|AM|^M/.freeze

changed_files = `git status --porcelain`
  .split(/\n/)
  .select { |f| f =~ ADDED_OR_MODIFIED }
  .map { |f| f.split(' ')[1] }
  .select { |f| File.extname(f) == '.rb' }
  .join(' ')

system("bundle exec rubocop #{changed_files} -a") unless changed_files.empty?

exit $?.to_s[-1].to_i
